name: dsenv_minimal
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - numpy=1.21.2
  - pandas=1.3.3
  - statsmodels=0.13.0
  - pybedtools=0.8.2
  - adjusttext=0.7.3.1
  - seaborn=0.11.2
  - xmlschema=1.8.0
  - requests=2.26.0
  - python-wget=3.2
  - biopython=1.79