name: dsenv
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - numpy=1.21.2
  - pandas=1.3.3
  - statsmodels=0.13.0
  - pybedtools=0.8.2
  - adjusttext=0.7.3.1
  - seaborn=0.11.2
  - mdanalysis=2.0.0
  - xmlschema=1.8.0
  - requests=2.26.0
  - python-wget=3.2
  - pybigwig=0.3.18
  - prody=2.0
  - root=6.24.6
  - pytest=6.2.5
  - pytest-mpl=0.13
  - pip=22.1.2
  - pip:
    - freesasa==2.1.0
